name-template: 'Release draft'
tag-template: 'draft'
categories:
  - title: '🚀 Features'
    labels:
      - '🎆 type:feature'
  - title: '🐛 Bug Fixes'
    labels:
      - '🐛 type:bug'
  - title: '🧰 Maintenance and others'
    labels: 
      - '🧫 type:test'
      - '🏨 scope:infrastructure'
      - '🛠 type:refactoring'
      - '📑 scope:docs'
      - '🧱 scope:build'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  [Milestone with issues list](https://github.com/lisa-analyzer/lisa/milestone/###MILESTONE_NUMBER###) 
  [Maven (sdk)](https://search.maven.org/artifact/io.github.lisa-analyzer/lisa-sdk/###TARGET_VERSION###/jar) - [Maven (analyses)](https://search.maven.org/artifact/io.github.lisa-analyzer/lisa-analyses/###TARGET_VERSION###/jar) - [Maven (program)](https://search.maven.org/artifact/io.github.lisa-analyzer/lisa-program/###TARGET_VERSION###/jar) - [Maven (imp)](https://search.maven.org/artifact/io.github.lisa-analyzer/lisa-imp/###TARGET_VERSION###/jar)
  [Javadoc (sdk)](https://javadoc.io/doc/io.github.lisa-analyzer/lisa-sdk/###TARGET_VERSION###) - [Javadoc (analyses)](https://javadoc.io/doc/io.github.lisa-analyzer/lisa-analyses/###TARGET_VERSION###) - [Javadoc (program)](https://javadoc.io/doc/io.github.lisa-analyzer/lisa-program/###TARGET_VERSION###) - [Javadoc (imp)](https://javadoc.io/doc/io.github.lisa-analyzer/lisa-imp/###TARGET_VERSION###)
  
  ## Changes

  $CHANGES
